version: "3.9"
services:
  db:
    container_name: database
    image: postgres:15.1
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - ./script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
        test: ["CMD-SHELL", "pg_isready --username=prisma --dbname=tests"]
        interval: 10s
        timeout: 5s
        retries: 5